### ISSUE TITLE
Downloader may break on server-side errors

### ISSUE THREAD

**Issue by hendrikmakait** [mara/google-adwords-performance-downloader#2]
The downloader may break on server-side errors. An example of a retry logic tackling this problem can be found at https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/v201702/reporting/parallel_report_download.py

**Comment by martin-loetzsch** [comment]
Solved with fa0d97270d4c4360581e2c60a335f3f5ba772f8b
